import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Header from "./components/Header";
import SidebarLayout from "./components/SidebarLayout";
import "bootstrap/dist/css/bootstrap.min.css";
import WebList from "./components/WebList";
import Sliders from "./components/Sliders";
import ShowBar from "./components/ShowBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container fluid className="min-vh-100">
          <Row>
            <Header />
            <Row xs={1} md={2}>
              <Col className="first-section" xs={12} md={4} lg={3}>
                <SidebarLayout />
              </Col>
              <Col style={{ flex: 1 }}>
                <WebList />
                <Sliders />
              </Col>
            </Row>
            {children}
          </Row>
        </Container>
      </body>
    </html>
  );
}
